/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'MarkPerry' at '24/02/14 10:40 AM' with Gradle 1.10
 *
 * @author MarkPerry, @date 24/02/14 10:40 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
