/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'MarkPerry' at '24/02/14 10:40 AM' with Gradle 1.10
 *
 * @author MarkPerry, @date 24/02/14 10:40 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
